services:
  - type: web
    name: dhospital
    env: python
    pythonVersion: "3.11"  # Use 3.11 instead of 3.13
    buildCommand: "./build.sh"
    startCommand: "gunicorn api.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: etha_hospitalreal_j8yz
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    staticFiles:
      - source: /media/
        destination: /media/